"""empty message

Revision ID: 178b66bd7db5
Revises: e8ede32de972
Create Date: 2024-04-04 20:00:05.645204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178b66bd7db5'
down_revision = 'e8ede32de972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
